### ISSUE TITLE
Python API script

### ISSUE THREAD

**Issue by drhodesbrc** [griffithlab/dgi-db#324]
The python API script in your API pages doesn't seem to work due to some encoding ascii/utf-8 issues (at least if not printing the output to the terminal). 
I think:
` def print_response(self):
        response = json.loads(self.response.content)
        matches = response['matchedTerms']
`
Should be:
` def print_response(self):
        response = json.loads(self.response.content.decode('utf-8'))
        matches = response['matchedTerms']
`

**Comment by ahwagner** [comment]
Thanks for reporting this @drhodesbrc! We're on it.

**Comment by ahwagner** [comment]
We have had a report that the DGIdb Python example is not working, specifics unclear. I've requested the user to follow-up here.

**Comment by wangerish1987** [comment]
Hi guys, my name is Jason and I'm trying to use DGIdb to essentially write a python code that would query the database, (i.e. for a list of drug targets) similar to the search interactions page of your website. From there, I'm trying to then populate a dataframe, and create curated pubmed searches. however while I appear to be able to call the API, I've had problems doing anything else. The python code sample on the website did not work for me at all. Do you have an example in either Jupyter or Spyder that you can share as a starting point? Thank you.

**Comment by wangerish1987** [comment]
Right now I'm just playing with the example provided:

import sys
import argparse
import json
import requests

def parse_args():
    parser = argparse.ArgumentParser(description = "A Python example for using the DGIdb API", epilog = "For complete API documentation refer to http://dgidb.org/api")
    parser.add_argument("-g", "--genes", help="list of gene symbols(REQUIRED). Use official Entrez symbols for best results", dest="genes")
    parser.add_argument("-is", "--interaction_sources", help="Limit results to those from particular data sources. e.g. 'DrugBank', 'PharmGKB', 'TALC', 'TEND', 'TTD', 'MyCancerGenome')", dest="interaction_sources")
    parser.add_argument("-it", "--interaction_types", help="Limit results to interactions with drugs that have a particular mechanism of action. e.g. 'inhibitor', 'antibody', etc", dest="interaction_types")
    parser.add_argument("-gc", "--gene_categories", help="Limit results to genes with a particular druggable gene type. e.g. 'KINASE', 'ION CHANNEL', etc", dest="gene_categories")
    parser.add_argument("-stl", "--source_trust_levels", help="Limit results based on trust level of the interaction source. e.g. 'Expert curated' or 'Non-curated", dest = "source_trust_levels")
    parser.add_argument("-ano", "--antineoplastic_only", help="Limit results to anti-cancer drugs only", dest="antineoplastic_only", action = 'store_true')
    parser.add_argument("-u", "--usage", help="Usage examples", dest="usage", action = 'store_true')
    return parser.parse_args()

class DGIAPI:
    'API Example class for DGI API.'
    domain = 'http://dgidb.org/'
    api_path = '/api/v1/interactions.json'
    def __init__(self, args):
        self.genes = args.genes
        self.interaction_sources = args.interaction_sources
        self.interaction_types = args.interaction_types
        self.gene_categories = args.gene_categories
        self.source_trust_levels = args.source_trust_levels
        self.antineoplastic_only = args.antineoplastic_only
    def run_workflow(self):
        self.create_request()
        self.post_request()
        self.print_response()
    def create_request(self):
        self.request = "http://dgidb.org/api/v1/interactions.json?genes=FLT1&drug_types=antineoplastic&interaction_sources=TALC"
        self.payload = {}
        if(self.genes):
            self.payload['genes'] = self.genes
        if(self.interaction_sources):
            self.payload['interaction_sources'] = self.interaction_sources
        if(self.gene_categories):
            self.payload['gene_categories'] = self.gene_categories
        if(self.interaction_types):
            self.payload['interaction_types'] = self.interaction_types
        if(self.source_trust_levels):
            self.payload['source_trust_levels'] = self.source_trust_levels
        if(self.antineoplastic_only):
            self.payload['drug_types'] = 'antineoplastic'
    def post_request(self):
        self.request = DGIAPI.domain + DGIAPI.api_path
        self.response = requests.post(self.request, data = self.payload)
    def print_response(self):
        response = json.loads(self.response.content.decode('utf-8'))
        matches = response['matchedterms']
        if(matches):
          print ("gene_name\tdrug_name\tinteraction_type\tsource\tgene_categories")
        for match in matches:
            gene = match['geneName']
            categories = match['geneCategories']
            categories.sort()
            joined_categories = ",".join(categories)
            for interaction in match['interactions']:
                source = interaction['source']
                drug = interaction['drugName']
                interaction_type = interaction['interactionType']
                print(gene + "\t" + drug + "\t" + interaction_type + "\t" + source + "\t" + joined_categories.lower())
        for unmatched in response['unmatchedTerms']:
            print ("Unmatched search term: " + unmatched['searchTerm'])
            print ("Possible suggestions: " + ",".join(unmatched['suggestions']))

if __name__ == '__main__':
    args = parse_args()
    da = DGIAPI(args)
    da.run_workflow()

**Comment by wangerish1987** [comment]
I'm getting this error, and without knowing how the code is working, it's tough for me to trouble shoot it: 


  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/jwang/OneDrive - Fortress Bio Tech/Python/Biopython/Test_drug_gene.py", line 72, in <module>
    da.run_workflow()

  File "C:/Users/jwang/OneDrive - Fortress Bio Tech/Python/Biopython/Test_drug_gene.py", line 31, in run_workflow
    self.print_response()

  File "C:/Users/jwang/OneDrive - Fortress Bio Tech/Python/Biopython/Test_drug_gene.py", line 52, in print_response
    matches = response['matchedterms']

KeyError: 'matchedterms'

**Comment by sunsong95** [comment]
> I'm getting this error, and without knowing how the code is working, it's tough for me to trouble shoot it:
> 
> File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
> execfile(filename, namespace)
> 
> File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
> exec(compile(f.read(), filename, 'exec'), namespace)
> 
> File "C:/Users/jwang/OneDrive - Fortress Bio Tech/Python/Biopython/Test_drug_gene.py", line 72, in
> da.run_workflow()
> 
> File "C:/Users/jwang/OneDrive - Fortress Bio Tech/Python/Biopython/Test_drug_gene.py", line 31, in run_workflow
> self.print_response()
> 
> File "C:/Users/jwang/OneDrive - Fortress Bio Tech/Python/Biopython/Test_drug_gene.py", line 52, in print_response
> matches = response['matchedterms']
> 
> KeyError: 'matchedterms'

 hi, I encountered the same problem, have you solved it now？thanks @Jason-Wang12

**Comment by acoffman** [comment]
It looks like the dictionary key is incorrect ('matchedterms' should be 'matchedTerms') based on that error message, however in the example our in repo: https://github.com/dgidb/dgidb/blob/master/files/python_example.py#L76 the key seems to be correct. Are you running an older version of the example script or one downloaded from somewhere other than this repo?

**Comment by mferreiradasilva** [comment]
I have ran into the same problem and the key is correct (````matchedTerms````).

**Comment by acoffman** [comment]
Hi @mferreiradasilva, can you provide me with the specific command you're trying to run so I can look into it further?

**Comment by mferreiradasilva** [comment]
Hi @acoffman, I'm just trying to run the example request.

````./python_example.py --genes='FLT3,EGFR' --interaction_types='inhibitor'````

````Traceback (most recent call last):
  File "./python_example.py", line 98, in <module>
    da.run_workflow()
  File "./python_example.py", line 55, in run_workflow
    self.print_response()
  File "./python_example.py", line 76, in print_response
    matches = response['matchedTerms']
KeyError: 'matchedTerms'````

**Comment by cgrisdale** [comment]
@mferreiradasilva I had the same problem and was able to solve it by updating this line:
`domain = 'http://dgidb.org/'`
to this:
`domain = 'https://dgidb.org/'`

There is a PR to fix this but it hasn't been merged yet.
